# Generated by Django 4.2.3 on 2023-10-07 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('channel_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='code')),
                ('display_name', models.CharField(max_length=50, verbose_name='Chaine')),
                ('icon_sc', models.CharField(max_length=500, verbose_name='Icon')),
                ('sort', models.IntegerField(default=0, verbose_name='Tri')),
            ],
            options={
                'verbose_name': 'Chaine',
                'verbose_name_plural': 'Chaines',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='ProgressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Début')),
                ('stop_time', models.DateTimeField(verbose_name='Fin')),
                ('day', models.DateField(verbose_name='Jour')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
                ('category', models.CharField(max_length=100, verbose_name='Catégorie')),
                ('genre', models.CharField(max_length=100, verbose_name='Genre')),
                ('length', models.IntegerField(default=0, verbose_name='Durée')),
                ('icon_sc', models.CharField(max_length=500, verbose_name='Icon')),
                ('rating', models.CharField(max_length=100, verbose_name='Rating')),
                ('status', models.IntegerField(default=0, verbose_name='Status')),
                ('year', models.IntegerField(default=0, verbose_name='Année')),
                ('actors', models.CharField(default='', max_length=100, verbose_name='Acteurs')),
                ('url_cover', models.CharField(default='', max_length=500, verbose_name='Affiche')),
                ('json_data', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_Programme_Channel', to='tv.channel')),
            ],
            options={
                'verbose_name': 'Programme',
                'verbose_name_plural': 'Programmes',
                'ordering': ['channel', 'start_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='programme',
            constraint=models.UniqueConstraint(fields=('channel', 'start_time'), name='unique_programme_key'),
        ),
    ]
